services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_DATA-FILE-PATH=/data/todos.json
    volumes:
      - ./backend/src/main/resources/todos.json:/data/todos.json
